CMM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.shortcuts import redirect

'''
##최상위 주소##
def root(request):
	return redirect('login:login')
'''
urlpatterns = [
	#url(r'^$', root, name='root'), ##최상위 주소##
	#url(r'^$', lambda r: redirect('login:login'), name='root'), ##최상위 주소##
    url(r'^admin/', admin.site.urls),
    url(r'^', include('login.urls', namespace='login')),
    url(r'^index/', include('main.urls')),
]

login/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #login하기위해
from . import views
from .views import *


urlpatterns = [
    
    url(r'^test/$', views.test, name='test'),

    #자유게시판
    url(r'^board/list/$', views.board_list, name='board_list'),
    url(r'^board/write/$', views.board_write, name='board_write'),
    url(r'^board/view/(?P<id>.+)/$', views.board_view, name='board_view'),
    url(r'^board/edit/(?P<id>.+)/$', views.board_edit, name='board_edit'),
    url(r'^board/delete/(?P<id>.+)/$', views.board_delete, name='board_delete'),
    
    #자유게시판댓글
    url(r'^(?P<post_pk>\d+)/act_comment/write/$', views.act_comment_write, name='act_comment_write'),
    url(r'^(?P<post_pk>\d+)/act_comment/(?P<pk>\d+)/edit/$', views.act_comment_edit, name='act_comment_edit'),
    url(r'^(?P<post_pk>\d+)/act_comment/(?P<pk>\d+)/delete/$', views.act_comment_delete, name='act_comment_delete'),

    #익명게시판
    url(r'^post/list/$', views.post_list, name='post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    #익명게시판 댓글
    url(r'^post/(?P<post_pk>\d+)/comment/new/$', views.comment_new, name='comment_new'),
    url(r'^post/(?P<post_pk>\d+)/comment/(?P<pk>\d)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^post/(?P<post_pk>\d+)/comment/(?P<pk>\d)/delete/$', views.comment_delete, name='comment_delete'),

    #통장관리
    url(r'^mypage/edit/(?P<id>.+)/$', views.account_edit, name='account_edit'),
    url(r'^mypage/delete/(?P<id>.+)/$', views.account_delete, name='account_delete'),    
    url(r'^index/my_list/(?P<id>.+)/$', views.my_list, name='my_list'),
    url(r'^index/my_view/(?P<id>.+)/$', views.my_view, name='my_view'),
    url(r'^index/my_edit/(?P<id>.+)/$', views.my_edit, name='my_edit'),
    url(r'^index/my_delete/(?P<id>.+)/$', views.my_delete, name='my_delete'),

    #회원가입
    url(r'^join/$', views.join, name='join'),

    #탈퇴
    url(r'^user_delete_confirm/$', DeleteConfirm.as_view(), name='user_delete_confirm'),
    url(r'^user_delete/$', delete_user, name='user_delete'),
    
    #비번변경
    url(r'^changepw/$', ChangePw, name='change_pw'),

    #이메일찾기
    url(r'^searchemail/$', SearchEmail.as_view(), name='search_email'),
    url(r'^findusername/$', find_username, name='find_username'),

    #비번찾기
    url(r'^searchpassword/$', SearchPassword.as_view(), name='search_password'), #폼 보여주는 템플릿
    url(r'^findpassword/$', FindPassword, name='find_password'),#폼에서 데이터 받아와서 처리
    url(r'^ForgetChangePw/(?P<email>.+)/$', ForgetChangePw, name='ForgetChangePw'),#조회결과가 있을시 서치

    #회원관리
    url(r'^index/$', views.index, name='index'),
    url(r'^mypage/$', views.Managment, name='Managment'),
    url(r'^mypage/PWC$', auth_views.password_change, name='password_change_done',
    	kwargs={'template_name': 'login/mypage.html'}),

    url(r'^mypage/(?P<id>.+)/$', views.account_view, name='account_view'), 
    url(r'^add/(?P<id>.+)/$', views.bankbook_new, name='bankbook_new'),
    #https://github.com/django/django/blob/1.10.6/ddjango/contrib/auth/views.py#L62
    #에 def login을 보면 기본 request받고 기본 디렉토리가 내가 설정한 것과 다르기 때문에 kwargs를 사용해 임의 지정 함
    url(r'^$', auth_views.login, name='login', 
    	kwargs={'template_name': 'login/login.html'}),
    url(r'^logout/', auth_views.logout, name='logout', 
        kwargs={'next_page': settings.LOGIN_URL}),
]

#이미지 업로드
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
#from .validators import number_validator
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from hitcount.models import HitCount, HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation
from django.conf import settings

from django.core.urlresolvers import reverse

#user는 django.contrib.auth.middleware.AuthenticationMiddlewar에 의해 설정됨
#https://github.com/django/django/blob/stable/1.10.x/django/contrib/auth/middleware.py#L16
class MyUserManager(BaseUserManager):
    def create_user(self, email, nickname, birth, password=None):
        if not email:
            raise ValueError('Users must have an email address')
 
        user = self.model(
            email=self.normalize_email(email),
            nickname=nickname,
            birth=birth,
        )
 
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, email, nickname,birth, password):
        user = self.create_user(
            email=email,
            password=password,
            nickname=nickname,
            birth=birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

#원래 User모델은 AbstractUser라는 애를 상속받고 있음
#AbstractUser이 더 큰 부모이기 떄문에 그녀석을 가져다가 쓸것임
#AbstractUser에 대한 정보는 아래 페이지
#https://github.com/django/django/blob/1.10.5/django/contrib/auth/models.py#L300
class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email',
        max_length=50,
        unique=True,
    )
    nickname = models.CharField(
        verbose_name='nickname',
        max_length=20,
        blank=False,
        unique=True,
        help_text='한글가능',
    )
    birth = models.DateField(
        verbose_name='birth',
        max_length=50,
        blank=False,
        unique=False,
        help_text='반드시 양식을 지켜주세요',
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
 
    objects = MyUserManager()
 
    USERNAME_FIELD = 'email'    # When username is required, You must use this field!
    REQUIRED_FIELDS = ['nickname','birth']
 
    def get_full_name(self):
        # The user is identified by their email address
        return self.email
 
    def get_short_name(self):
        # The user is identified by their email address
        return self.email
 
    def __str__(self):              # __unicode__ on Python 2
        return self.email
 
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
 
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
 
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

##로그아웃 유저를 표현할 파이썬 클래스 (NOT 모델)
class AnonymouseUser:
    id = None
    pk = None
    nickname = ''
    is_staff = False
    birth = ''


class ActList(models.Model):
    act = models.ForeignKey(MyUser)
    act_num = models.CharField(
        max_length=15,
        verbose_name='계좌번호',
        null=False,
        blank=False,
        unique=True,
        #validators=[number_validator],
    )
    act_name = models.CharField(
        max_length=20,
        verbose_name='통장이름',
        null=False,
        blank=False,
    )
    act_summary = models.CharField(
        max_length=50,
        verbose_name='한줄설명',
        null=True,
        blank=False,
    )
    act_info = models.TextField(
        max_length=50,
        verbose_name='통장정보',
        null=False,
        blank=True,
    )
    def __str__(self):
       return "{}".format(self.act)

    

class BankBook(models.Model):
    name = models.ForeignKey(ActList)

    #날짜
    act_date = models.DateField(
        null=False,
        verbose_name='날짜',
        )
    
    #금액
    act_price = models.IntegerField(
        null=False,
        verbose_name='금액',
        ) 
    
    #카드(T)/현금(F)
    act_payment = models.CharField(
        verbose_name='카드/현금',
        max_length=6,
        )
    
    #수입(T)/지출(F)
    act_part = models.CharField(
        verbose_name='수입/지출',
        max_length=6,
        )

    #남은돈
    act_total = models.IntegerField(
        verbose_name='잔여금액',
        default=0,
        )

    #코멘트
    act_content = models.CharField(
        verbose_name='소비내용',
        max_length=50,
        default=' '
        )

    def __str__(self):
        return "{} / {} 의 {}".format(self.act_date, self.name, self.act_part)


##자유게시판
class ActBoard(models.Model):
    board_name = models.ForeignKey(MyUser)

    #글제목
    board_title = models.CharField(
        verbose_name='글제목',
        max_length=40,
        )

    #닉네임
    board_nick = models.CharField(
        verbose_name='닉네임',
        max_length=40,
        )

    #글내용
    board_content = models.CharField(
        verbose_name='글내용',
        max_length=3000,
        )

    #작성시간
    create_time = models.DateTimeField(
        verbose_name='작성시간',
        auto_now_add=True
        )

    #업데이트 시간
    update_time = models.DateTimeField(
        verbose_name='작성시간',
        auto_now=True,
        )

    board_hit = models.IntegerField(
        verbose_name='조회',
        default=0,
        )

    #조회
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')

    def __str__(self):
        return self.board_title

##자유게시판 댓글
class ActComment(models.Model):
    #ActBoard : ActComment = 1 : N
    act_post = models.ForeignKey(ActBoard)
    act_author = models.ForeignKey(settings.AUTH_USER_MODEL)#로그인을 해야만 댓글남김
    act_message = models.TextField(
        verbose_name='댓글내용'
        )
    act_created_at = models.DateTimeField(auto_now_add=True)
    act_updated_at = models.DateTimeField(auto_now=True)
    act_count = models.IntegerField(default=0)

    class Meta:
        ordering = ['-id'] #기본정렬 방식을 id의 역순으로

    
    #수정 url
    def get_edit_url(self):
        return reverse('login:act_comment_edit', args=[self.act_post.pk, self.pk])

    #삭제 url
    def get_delete_url(self):
        return reverse('login:act_comment_delete', args=[self.act_post.pk, self.pk])

    def get_absolute_url(self):
        return reverse('login:board_view', args=[self.pk])


##익명게시판
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(blank=True)
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    writer = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']


##익명게시판 댓글
class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.message

    #수정 url
    def get_edit_url(self):
        return reverse('login:comment_edit', args=[self.post.pk, self.pk])

    #삭제 url
    def get_delete_url(self):
        return reverse('login:comment_delete', args=[self.post.pk, self.pk])

    def get_absolute_url(self):
        return reverse('login:board_view', args=[self.pk])

login/templates/login/bankbook.html
{% extends 'login/layout.html' %}

{% block content %}

<!--돈입력버튼-->
<div class="py-5">
  <div class="container">    
    <!--입력 폼-->
    <form action="" method="post">
    {% csrf_token %}
      <center>
        <!--폼에 필드가 없을경우 에러메세지 출력-->
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ error }}
          </div>
        {% endfor %}

        <div class="col-sm-5 form-control">
          {% for ActList in qs %}
            <h1 class="text-primary">{{ActList.act_name}} 입력</h1>
          {% endfor %}
          <input type="date" class="form-control" id="id_act_date" name="act_date">
          {% for error in form.act_date.errors %}
            <div class="alert alert-danger">
              {{ error }}
            </div>
          {% endfor %}
          <input type="text" class="form-control" id="id_act_price" name="act_price" placeholder="금액(원)">
          {% for error in form.act_price.errors %}
            <div class="alert alert-danger">
              {{ error }}
            </div>
          {% endfor %}
          <select class="form-control" id="id_act_payment" name="act_payment">
            <option>카드</option>
            <option>현금</option>
            <option> </option>
          </select>
          <select class="form-control" id="id_act_part" name="act_part">
            <option>수입</option>
            <option>지출</option>
            <option> </option>
          </select>

          <input list="id_act_content" name="act_content" class="form-control" placeholder="메모(직접입력 가능)">
          <datalist id="id_act_content" name="act_content">
            <option>월급</option>
            <option>적금</option>
            <option>교통비</option>
            <option>식비</option>
            <option>여가비</option>
          </datalist>
          {% for error in form.act_content.errors %}
            <div class="alert alert-danger">
              {{ error }}
            </div>
          {% endfor %}
          <p class="help-block"></p><!--공백용-->
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">완료</button>
          <a href="/index" class="btn btn-outline-danger my-2">취소</a>
        </div>    
      </center>
    </form>
  </div>
  <!--입력폼 끝-->
</div>
{% endblock %}

login/templates/login/board_view.html
{% extends 'login/layout.html' %}

{% block content %}
<div class="py-5">
	<div class="container">
		<div class="row">
		<div class="col-sm-2">
		</div>
		<div class="col-sm-8">
			<center>
				<h1 class="text-primary">게시글 보기</h1>
			</center>
			<br>
			<form>
				<table class="table">
					{% for ActBoard in qs_board_view %}
						<tr>
							<td width="150px">
								<h3 class="text-primary">글제목</h3>
							</td>
							<td>
								<label>{{ ActBoard.board_title }}</label>
							</td>
						</tr>
						<tr>
							<td>
								<h4 class="text-primary">글쓴이</h4>
							</td>
							<td>
								<label>{{ ActBoard.board_nick }}</label>
							</td>
						</tr>
						<tr>
							<td>
								<h4 class="text-primary">시간</h4>
							</td>
							<td>
								<label>{{ ActBoard.create_time }}</label>
							</td>
						</tr>
						<tr>
							<td>
								<h4 class="text-primary">글내용</h4>
							</td>
							<td>
								<label>{{ ActBoard.board_content }}</label>
							</td>
						</tr>
				</table>
				<hr>
				<td><h4 class="text-primary">댓글</h4></td>
				<ul>
					{% if not post.actcomment_set.all %}
							아직 입력된 댓글이 없습니다
					{% endif %}
					{% for ActComment in post.actcomment_set.all %}
						<li>
							{{ ActComment.act_message }}
							<strong>by</strong> {{ ActComment.act_author.nickname }}
							<strong>at</strong> {{ ActComment.act_created_at }}
							{% if ActComment.act_author == request.user %}
								<a href="{{ ActComment.get_edit_url }}">수정</a>
								<a href="{{ ActComment.get_delete_url }}" class="text-danger">삭제</a>
							{% endif %}
						</li>
					{% endfor %}
				</ul>
				<center>
					<hr>
						
					<a href="/board/list/" class="btn btn-outline-success">목록</a>
					<a href="/{{ActBoard.id}}/act_comment/write" class="btn btn-outline-primary">댓글쓰기</a>
				{% if user == ActBoard.board_name %}
					<a href="/board/edit/{{ActBoard.id}}" class="btn btn-outline-info">수정</a>
					<a href="/board/delete/{{ActBoard.id}}" class="btn btn-outline-danger">삭제</a>
				{% endif %}
				</center>
				{% endfor %}
			</form>
			<ul>
						
		</div>
		<div class="col-sm-2">
		</div>
		</div><!--End of row-->
	</div><!--End of container-->
</div><!--End of py-5-->
{% endblock %}

login/templates/login/comment_confirm_delete.html
<form action="" method="post">
	{% csrf_token %}
	정말 삭제 하시겠습니까?
	<input type="submit" value="삭제하겠습니다."/>	
</form>

login/templates/login/login.html
{% load static %}

<html>

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<br>
<br>
  <div class="container">
    <div class="row">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src="{% static "/img/main1.jpg" %}" alt="Los Angeles" style="width:40%; ">
            <div class="carousel-caption">
            <h1 class="text-primary"><strong>통장별로 관리하고</strong></h1>
            <p class="text-primary"><strong></strong></p>
          </div>
          </div>

          <div class="item">
            <img src="{% static "/img/main2.jpg" %}" alt="Chicago" style="width:40%; ">
            <div class="carousel-caption">
            <h1 class="text-primary"><strong>보기쉬운 그래프와</strong></h1>
            <p></p>
          </div>
          </div>
        
          <div class="item">
            <img src="{% static "/img/main3.jpg" %}" alt="New york" style="width:40%; ">
            <div class="carousel-caption">
            <h1 class="text-primary"><strong>상담 까지!</strong></h1>
            <p></p>
          </div>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>



<!--몸통부분-->
<div class="container">
  <div class="row">
  <hr>
    <div class="col-md-4"><img src="{% static "/img/logoo.png" %}" width="200"></div>
    <div class="col-md-4">
      <h1 class=" pi-item">CMM Project</h1>
      <p> <strong>Control My Money, Inc.</strong> <br>여러분의 새는돈을 지켜드립니다. <br>CMM은 무료 서비스입니다. <br> <abbr title="Phone">P:</abbr>(123) 456-7890 </p>
    </div>
    <div class="col-md-4">
      <h1 class="pi-item">LOGIN</h1>
      <form action="" method="post">
      {% csrf_token %}
        <table>
          {{form.as_table}}
        </table>
        <!--
        <fieldset class="form-group"> <label for="exampleInputEmail1">ID</label> 
        {{ form.email }}
        </fieldset>

        <fieldset class="form-group"> <label for="exampleInputEmail1">Password</label> 
        {{ form.password }}
        </fieldset>
        -->
        <center>
          <button type="submit" class="btn btn-primary">Sign in</button>
          <a class="btn btn-primary" href="{% url 'login:join' %}">Sign up</a> 
          <br>
          <a href="{% url 'login:search_email' %}">아이디 찾기</a>
          <a href="{% url 'login:search_password' %}">비번 찾기</a>
        </center>
      </form>
    </div>

  </div>
  <hr>
</div>


</body>

</html>

login/templates/login/my_delete_identification.html
{% extends "login/mypage_layout.html" %}

{% block title %}identification.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}

<div class="section">       
    <div class="title-area">
        <p class="description">본인 확인을 위해 비밀번호를 입력해주세요!</p>
        <form method="post" action="{% url 'login:user_delete' %}"> 
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-warning">
              <strong>Warning!</strong> {{form.errors}}
            </div>
        {% endif %}
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">
                <i class="fa fa-lock" aria-hidden="true"></i>
            </span>
                <input type="password" class="form-control" name="password" required="" id="id_password" placeholder="password">
        </div>
        <div class="py-2">
            <div class="submit-row">
                <input type="submit" class ="btn btn-danger btn-fill btn-md" value="탈퇴하기"/>
                <input type="hidden" name="next" value="{{ next }}" />
            </div>       
            <script type="text/javascript">document.getElementById("id_username").focus();
            </script>
        </div>
        </form>
    </div>
</div>
{% endblock %}

login/templates/login/my_edit.html
{% extends 'login/layout.html' %}

{% block content %}

<div class="py-3">
  <form action="" method="post">
      {% csrf_token %}
  	     <center>
          <!--폼에 필드가 없을경우 에러메세지 출력-->
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
          {% endfor %}
          <div class="col-sm-5 form-control" >
          <h1 class="text-primary"><center>계좌정보</center></h1><br>
          <input type="text" class="form-control" id="id_act_date" name="act_date" value="{{ form.act_date.value }}">
            {% for error in form.act_date.errors %}
              <div class="alert alert-danger">
                {{ error }}
              </div>
            {% endfor %}
            <input type="text" class="form-control" required id="id_act_price" name="act_price" value="{{ form.act_price.value }}">
            {% for error in form.act_price.errors %}
              <div class="alert alert-danger">
                {{ error }}
              </div>
            {% endfor %}

            <select class="form-control" id="id_act_payment" name="act_payment">

              <option>{{form.act_payment.value}}</option>
              
              {% if form.act_payment.value == "현금" %}
  	       		<option>카드</option>
  	        {% else %}
  	            <option>현금</option>
              {% endif %}
            </select>
            <select class="form-control" id="id_act_part" name="act_part">
              <option>{{form.act_part.value}}</option>
              
              {% if form.act_part.value == "수입" %}
              	<option>지출</option>
              {% else %}
              	<option>수입</option>
            	{% endif %}
            </select>
            <input list="id_act_content" name="act_content" class="form-control" value="{{form.act_content.value}}">
            <datalist id="id_act_content" name="act_content">
              <option>월급</option>
              <option>적금</option>
              <option>교통비</option>
              <option>식비</option>
              <option>여가비</option>
            </datalist>
            {% for error in form.act_price.errors %}
              <div class="alert alert-danger">
                {{ error }}
              </div>
            {% endfor %}
          <p class="help-block"></p>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">완료</button>
          </center>
          </div> 
  </form>
</div>
{% endblock %}

login/templates/login/search_email.html
{% load static %}

<html>

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<br>
<br>
  <div class="container">
    <div class="row">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <div class="item active">
            <img src="{% static "/img/main1.jpg" %}" alt="Los Angeles" style="width:40%; ">
            <div class="carousel-caption">
            <h1 class="text-primary"><strong>통장별로 관리하고</strong></h1>
            <p class="text-primary"><strong></strong></p>
          </div>
          </div>

          <div class="item">
            <img src="{% static "/img/main2.jpg" %}" alt="Chicago" style="width:40%; ">
            <div class="carousel-caption">
            <h1 class="text-primary"><strong>보기쉬운 그래프와</strong></h1>
            <p></p>
          </div>
          </div>
        
          <div class="item">
            <img src="{% static "/img/main3.jpg" %}" alt="New york" style="width:40%; ">
            <div class="carousel-caption">
            <h1 class="text-primary"><strong>상담 까지!</strong></h1>
            <p></p>
          </div>
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>

<div class="container">
    <div class="row">
    <hr>
        <div class="col-sm-12">
            <div class="section">       
                <div class="title-area">
                    <h1 class="text-primary">아이디 찾기</h1>
                    <p class="description">가입 당시 입력했던 닉네임과 생년월일을 입력하세요!</p>
                        <form method="post" action="{% url 'login:find_username' %}"> 
                            {% csrf_token %}

                            {% if form.errors %}
                            <div class="alert alert-warning">
                              <strong>Warning!</strong> {{form.errors}}
                            </div>
                            {% endif %}
                            <table class="table">
                                <tr>
                                    <td>
                                        <input type="nickname" name="nickname" required="" placeholder="nickname" class="form-control" id="id_nickname">
                                    </td>
                                    <td>
                                        <input type="submit" class ="btn btn-danger" value="아이디찾기"/>      
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <input type="birth" name="birth" required="" placeholder="birthday: 2017-01-01" class="form-control" id="id_birth">
                                    </td>
                                    <td>
                                        <a href="/" class ="btn btn-primary">돌아가기</a>
                                    </td>
                                </tr>

                            </table>
                            <input type="hidden" name="next" value="{{ next }}" />
                            <script type="text/javascript">document.getElementById("id_username").focus();</script>
                        </form>
                </div>
            </div>
        </div><!--End of col-sm-12-->
    </div><!--End of row-->
</div><!--End of container-->

<center>
    {% for form in Useremail %}
        <h2> 당신의 아이디는 "{{ form.email }}". 입니다</h2>
        <a href="{% url 'login:login' %}">로그인하러 가기</a>
    {% endfor %} 

</center>
</body>
</html> 